apiVersion: apps/v1
kind: Deployment
metadata:
  name: obo-app
  labels:
    app: obo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obo
  template:
    metadata:
      labels:
        app: obo
    spec:
      containers:
      - name: obo-app
        image: orezfu/obo:v1.2
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: jdbc:mysql://10.0.2.15:3336/obo?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
